import json
import os
import pandas as pd
from flask import Flask, jsonify, send_file

app = Flask(__name__)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

@app.route('/')
def index():
    """Serve the AQI dashboard frontend."""
    return send_file(os.path.join(ROOT, 'aqi', 'frontend.html'))

@app.route('/api/data')
def get_dashboard_data():
    """Serve the full dashboard JSON (generated by pipeline.py)."""
    json_path = os.path.join(ROOT, 'data', 'aqi_dashboard_data.json')
    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
        return jsonify(data)
    except FileNotFoundError:
        return jsonify({"error": "Dashboard data not found. Run aqi/pipeline.py first."}), 404
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/forecast')
def get_forecast():
    """Serve the hourly 3-day forecast CSV as JSON."""
    csv_path = os.path.join(ROOT, 'data', 'lahore_aqi_3day_forecast.csv')
    try:
        df = pd.read_csv(csv_path)
        return jsonify({"status": "success", "data": df.to_dict(orient='records')})
    except FileNotFoundError:
        return jsonify({"status": "error", "message": "Forecast CSV not found."}), 404
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

if __name__ == '__main__':
    print("Starting Pearls AQI Dashboard on http://127.0.0.1:5000")
    app.run(debug=True, port=5000)
